<#
.SYNOPSIS
    Builds Infolume and verifies the packaged binary still works.

.DESCRIPTION
    Two things in this app break silently under trimming or NativeAOT: the
    reflection that reads NotifyIcon's private fields, and the IPolicyConfig COM
    interface used to switch the default device. Neither fails at build time, so
    this script runs the packaged exe's --selftest and asserts on the result
    rather than assuming a clean build means a working one.

    The unit tests under tests/ run first and are fatal: they cover the pure
    logic (glyph resolution, the learned tray-icon rect, settings round-trip and
    the tooltip cap), none of which needs a tray, a device or a display.

    Every mode is verified the same way. A framework-dependent build is a
    different binary with a different startup path, so "the self-contained one
    passed" says nothing about it.

.PARAMETER Mode
    SelfContained (default) - one ~48 MB exe, no runtime needed anywhere.
    Framework               - one ~2.1 MB exe, needs the .NET 10 Desktop Runtime.
    Both                    - both of the above, each verified in turn.

.PARAMETER Package
    Also produce the release assets under dist\release: one zip per mode
    containing the exe and LICENSE, and SHA256SUMS.txt covering them.

.EXAMPLE
    .\build.ps1
    .\build.ps1 -Mode Framework
    .\build.ps1 -Mode Both -Package     # everything a release needs, one command
#>
[CmdletBinding()]
param(
    [ValidateSet('SelfContained', 'Framework', 'Both')]
    [string]$Mode = 'SelfContained',

    [string]$Configuration = 'Release',

    [switch]$Package
)

$ErrorActionPreference = 'Stop'
$root    = $PSScriptRoot
$project = Join-Path $root 'src\Infolume\Infolume.csproj'
$tests   = Join-Path $root 'tests\Infolume.Tests\Infolume.Tests.csproj'

$modes = if ($Mode -eq 'Both') { @('SelfContained', 'Framework') } else { @($Mode) }

# Asset names carry the version, so it has to come from the same place the
# binary gets it rather than being typed in twice.
[xml]$csproj = Get-Content $project
$version = ($csproj.Project.PropertyGroup.Version | Where-Object { $_ }) | Select-Object -First 1
if (-not $version) { throw 'could not read <Version> from the csproj' }

Write-Host "Building Infolume $version ($($modes -join ' + '))..." -ForegroundColor Cyan

# The app icon is generated by the app itself, so the shell icon can never drift
# from the tray icon. Bootstrap past the circular dependency on first build by
# blanking ApplicationIcon for the throwaway compile that produces the generator.
$icoPath = Join-Path $root 'src\Infolume\app.ico'
Write-Host '  generating app.ico...' -ForegroundColor DarkGray
dotnet build $project -c Debug -v q --nologo -p:ApplicationIcon= | Out-Null
if ($LASTEXITCODE -ne 0) { throw 'bootstrap build failed' }
$bootstrap = Get-ChildItem (Join-Path $root 'src\Infolume\bin\Debug') -Recurse -Filter Infolume.exe |
             Sort-Object LastWriteTime -Descending | Select-Object -First 1
& $bootstrap.FullName --make-icon $icoPath
Start-Sleep -Milliseconds 500
if (-not (Test-Path $icoPath)) { throw 'Failed to generate app.ico' }

# --- unit tests -------------------------------------------------------------
# Ahead of the publish on purpose: a logic regression should stop the build
# without first spending a minute producing a 48 MB self-contained exe. The test
# project is never published - nothing here or in the publish below references
# it, so it cannot reach dist/. Run once, not once per mode: the tests exercise
# the same IL either way.
Write-Host 'Running unit tests...' -ForegroundColor Cyan
dotnet test $tests -c $Configuration -v q --nologo
if ($LASTEXITCODE -ne 0) { throw "unit tests failed ($LASTEXITCODE)" }

function Publish-Mode {
    param([string]$m)

    $outDir = Join-Path $root "dist\$($m.ToLower())"
    $publishArgs = @(
        'publish', $project,
        '-c', $Configuration,
        '-o', $outDir,
        '-v', 'q', '--nologo'
    )
    if ($m -eq 'Framework') {
        $publishArgs += @(
            '--self-contained', 'false',
            '-p:PublishReadyToRun=false',
            '-p:EnableCompressionInSingleFile=false'
        )
    }

    dotnet @publishArgs
    if ($LASTEXITCODE -ne 0) { throw "publish failed for $m ($LASTEXITCODE)" }

    $exe = Join-Path $outDir 'Infolume.exe'
    if (-not (Test-Path $exe)) { throw "no exe produced at $exe" }
    Write-Host ("  {0:N1} MB  {1}" -f ((Get-Item $exe).Length / 1MB), $exe) -ForegroundColor Green
    return $exe
}

function Test-PackagedBinary {
    param([string]$exe, [string]$m)

    Write-Host "Verifying packaged binary ($m)..." -ForegroundColor Cyan

    $log = Join-Path $env:TEMP "infolume-build-verify-$($m.ToLower()).log"
    Remove-Item $log -Force -ErrorAction SilentlyContinue
    $env:INFOLUME_LOG = $log

    # A running instance holds the single-instance mutex and would make the
    # selftest exit immediately. This is also why a build takes the machine-wide
    # build lock: it kills whatever Infolume the user is running.
    Get-Process Infolume -ErrorAction SilentlyContinue | Stop-Process -Force
    Start-Sleep -Milliseconds 400

    Start-Process -FilePath $exe -ArgumentList '--selftest' -Wait
    Start-Sleep -Milliseconds 800
    Remove-Item Env:\INFOLUME_LOG -ErrorAction SilentlyContinue

    if (-not (Test-Path $log)) { throw "selftest produced no log - the packaged exe did not run ($m)" }
    $content = Get-Content $log -Raw

    $checks = @(
        @{ Name = 'COM interop (IPolicyConfig)'; Pattern = 'IPolicyConfig round-trip: OK' }
        @{ Name = 'Flyout builds and shows';     Pattern = 'flyout\s+showing at' }
        @{ Name = 'Audio endpoints enumerated';  Pattern = 'endpoints=[1-9]' }
    )

    $failed = $false
    foreach ($c in $checks) {
        if ($content -match $c.Pattern) {
            Write-Host "  PASS  $($c.Name)" -ForegroundColor Green
        } else {
            Write-Host "  FAIL  $($c.Name)" -ForegroundColor Red
            $failed = $true
        }
    }
    if ($content -match 'EXCEPTION') {
        Write-Host '  FAIL  exceptions in selftest log' -ForegroundColor Red
        $content -split "`n" | Select-String 'EXCEPTION' | ForEach-Object { Write-Host "        $_" -ForegroundColor Red }
        $failed = $true
    }

    if ($failed) { throw "packaged binary failed verification ($m) - see $log" }
    Write-Host "OK: $exe" -ForegroundColor Green
}

# Each asset name states its own runtime requirement, so neither can be picked by
# accident by someone who does not know what a .NET runtime is.
#
# "includes" and "requires" are also chosen for sort order. GitHub lists release
# assets alphabetically with no way to reorder them, and a hyphen (0x2D) sorts
# before a dot (0x2E), so a plain Infolume-x.y.z-win-x64.zip would always be
# listed BELOW anything carrying a hyphenated suffix. Naming both halves puts
# "includes" above "requires" and the default download on top, where it belongs.
function Get-AssetName {
    param([string]$m)
    switch ($m) {
        'SelfContained' { "Infolume-$version-win-x64-includes-dotnet10.zip" }
        'Framework'     { "Infolume-$version-win-x64-requires-dotnet10.zip" }
    }
}

$built = @()
foreach ($m in $modes) {
    $exe = Publish-Mode $m
    Test-PackagedBinary -exe $exe -m $m
    $built += [pscustomobject]@{ Mode = $m; Exe = $exe }
}

if (-not $Package) {
    Write-Host ''
    Write-Host 'Built:' -ForegroundColor Cyan
    $built | ForEach-Object { Write-Host ("  {0,-14} {1,6:N1} MB  {2}" -f $_.Mode, ((Get-Item $_.Exe).Length / 1MB), $_.Exe) }
    return
}

# --- release assets ---------------------------------------------------------
# Both builds are zipped, including the 2.1 MB one. The zip is how LICENSE
# travels with the binary, which MIT actually requires, and it keeps the
# verification instructions identical for both downloads.
Write-Host ''
Write-Host 'Packaging release assets...' -ForegroundColor Cyan

$releaseDir = Join-Path $root 'dist\release'
Remove-Item $releaseDir -Recurse -Force -ErrorAction SilentlyContinue
New-Item -ItemType Directory -Path $releaseDir -Force | Out-Null

$licence = Join-Path $root 'LICENSE'
if (-not (Test-Path $licence)) { throw 'LICENSE not found - it has to ship with the binary' }

foreach ($b in $built) {
    $zipName = Get-AssetName $b.Mode
    $zipPath = Join-Path $releaseDir $zipName

    # Staged so the archive holds exactly two files at its root and nothing from
    # the publish directory leaks in.
    $stage = Join-Path $env:TEMP "infolume-pkg-$($b.Mode.ToLower())"
    Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue
    New-Item -ItemType Directory -Path $stage -Force | Out-Null
    Copy-Item $b.Exe (Join-Path $stage 'Infolume.exe')
    Copy-Item $licence (Join-Path $stage 'LICENSE')

    Compress-Archive -Path (Join-Path $stage '*') -DestinationPath $zipPath -Force
    Remove-Item $stage -Recurse -Force -ErrorAction SilentlyContinue

    Write-Host ("  {0,6:N1} MB  {1}" -f ((Get-Item $zipPath).Length / 1MB), $zipName) -ForegroundColor Green
}

# sha256sum format - two spaces - so `sha256sum -c SHA256SUMS.txt` works as well
# as the PowerShell one-liner the README gives.
$sumsPath = Join-Path $releaseDir 'SHA256SUMS.txt'
Get-ChildItem $releaseDir -Filter *.zip | Sort-Object Name | ForEach-Object {
    "{0}  {1}" -f (Get-FileHash $_.FullName -Algorithm SHA256).Hash.ToLower(), $_.Name
} | Set-Content $sumsPath -Encoding ascii

Write-Host ''
Write-Host "Release assets in $releaseDir" -ForegroundColor Cyan
Get-Content $sumsPath | ForEach-Object { Write-Host "  $_" }
